const fs = require('fs');

const items = [
  {
    no: 1,
    name: 'Acetic Acid',
    quantity: '2',
    unit: 'Cans',
    purityNotes: 'Can',
    formula: 'CH₃COOH',
    formulaPlain: 'CH3COOH',
    category: 'Chemical',
    location: 'Acid Cabinet',
    block: 'Acid Cabinet',
    grade: 'Glacial',
    casNumber: '64-19-7',
    hazardClass: 'Corrosive / Flammable Liquid',
    notes: 'Packaging: Can. Glacial organic carboxylic acid.'
  },
  {
    no: 2,
    name: 'Acetone',
    quantity: '3',
    unit: 'Bottles',
    purityNotes: '',
    formula: 'CH₃COCH₃',
    formulaPlain: 'CH3COCH3',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '67-64-1',
    hazardClass: 'Flammable Liquid / Irritant',
    notes: 'Volatile organic ketone solvent for organic synthesis and cleaning.'
  },
  {
    no: 3,
    name: 'Butanol',
    quantity: '',
    unit: '',
    purityNotes: '',
    formula: 'C₄H₉OH',
    formulaPlain: 'C4H9OH',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '71-36-3',
    hazardClass: 'Flammable Liquid / Irritant',
    notes: '1-Butanol / n-Butyl alcohol organic solvent.'
  },
  {
    no: 4,
    name: 'Calcium Chloride Dihydrate',
    quantity: '3',
    unit: 'Bottles',
    purityNotes: 'Powder',
    formula: 'CaCl₂·2H₂O',
    formulaPlain: 'CaCl2.2H2O',
    category: 'Chemical',
    location: 'Main Storage',
    block: 'Main Storage',
    grade: 'Powder',
    casNumber: '10035-04-8',
    hazardClass: 'Eye Irritant',
    notes: 'Form: Powder. Inorganic salt and drying agent / desiccant.'
  },
  {
    no: 5,
    name: 'Chlorobenzene',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'C₆H₅Cl',
    formulaPlain: 'C6H5Cl',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '108-90-7',
    hazardClass: 'Flammable Liquid / Toxic',
    notes: 'Aromatic halogenated organic solvent.'
  },
  {
    no: 6,
    name: 'Cyclohexanone',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'C₆H₁₀O',
    formulaPlain: 'C6H10O',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '108-94-1',
    hazardClass: 'Flammable Liquid / Harmful',
    notes: 'Cyclic ketone organic solvent.'
  },
  {
    no: 7,
    name: 'Diethyl Carbonate',
    quantity: '2',
    unit: 'Bottles',
    purityNotes: '',
    formula: 'C₅H₁₀O₃',
    formulaPlain: 'C5H10O3',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '105-58-8',
    hazardClass: 'Flammable Liquid',
    notes: 'Ethyl ester of carbonic acid, electrolyte solvent.'
  },
  {
    no: 8,
    name: 'Diethyl Ether',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: '(C₂H₅)₂O',
    formulaPlain: '(C2H5)2O',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '60-29-7',
    hazardClass: 'Extremely Flammable Liquid',
    notes: 'Highly volatile, flammable ether solvent.'
  },
  {
    no: 9,
    name: 'Dimethyl Carbonate',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'C₃H₆O₃',
    formulaPlain: 'C3H6O3',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '616-38-6',
    hazardClass: 'Highly Flammable Liquid',
    notes: 'Methylating agent and organic solvent.'
  },
  {
    no: 10,
    name: 'Dimethyl Sulphoxide (DMSO)',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: '(CH₃)₂SO',
    formulaPlain: '(CH3)2SO',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '67-68-5',
    hazardClass: 'Combustible Liquid',
    notes: 'Polar aprotic solvent.'
  },
  {
    no: 11,
    name: 'Ethyl Acetate',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'CH₃COOCH₂CH₃',
    formulaPlain: 'CH3COOCH2CH3',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '141-78-6',
    hazardClass: 'Highly Flammable Liquid / Eye Irritant',
    notes: 'Organic ester solvent.'
  },
  {
    no: 12,
    name: 'Ethyl Alcohol',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'C₂H₅OH',
    formulaPlain: 'C2H5OH',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '64-17-5',
    hazardClass: 'Highly Flammable Liquid',
    notes: 'Absolute Ethanol alcohol solvent.'
  },
  {
    no: 13,
    name: 'Ethylene Carbonate',
    quantity: '2',
    unit: 'Bottles',
    purityNotes: '99% (One in refrigerator)',
    formula: 'C₃H₄O₃',
    formulaPlain: 'C3H4O3',
    category: 'Chemical',
    location: 'Storage / Refrigerator',
    block: 'Refrigerator',
    grade: '99%',
    casNumber: '96-49-1',
    hazardClass: 'Harmful / Eye Irritant',
    notes: 'Purity: 99%. 1 bottle in general storage, 1 bottle in Refrigerator.'
  },
  {
    no: 14,
    name: 'Formaldehyde Solution',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'CH₂O',
    formulaPlain: 'CH2O',
    category: 'Chemical',
    location: 'Main Storage',
    block: 'Main Storage',
    grade: 'Solution',
    casNumber: '50-00-0',
    hazardClass: 'Toxic / Carcinogen / Corrosive',
    notes: 'Aqueous formalin solution.'
  },
  {
    no: 15,
    name: 'Formic Acid',
    quantity: '2',
    unit: 'Bottles',
    purityNotes: '98%',
    formula: 'HCOOH',
    formulaPlain: 'HCOOH',
    category: 'Chemical',
    location: 'Acid Cabinet',
    block: 'Acid Cabinet',
    grade: '98%',
    casNumber: '64-18-6',
    hazardClass: 'Corrosive / Flammable Liquid',
    notes: 'Purity: 98%. Methanoic acid, corrosive carboxylic acid.'
  },
  {
    no: 16,
    name: 'Glycerin',
    quantity: '',
    unit: '',
    purityNotes: '',
    formula: 'C₃H₈O₃',
    formulaPlain: 'C3H8O3',
    category: 'Chemical',
    location: 'Main Storage',
    block: 'Main Storage',
    grade: 'Pure',
    casNumber: '56-81-5',
    hazardClass: 'Non-Hazardous Reagent',
    notes: 'Glycerol, viscous triol compound.'
  },
  {
    no: 17,
    name: 'Heptane',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'C₇H₁₆',
    formulaPlain: 'C7H16',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '142-82-5',
    hazardClass: 'Highly Flammable Liquid / Aspiration Hazard',
    notes: 'Non-polar alkane hydrocarbon solvent.'
  },
  {
    no: 18,
    name: 'H₂O₂ (Hydrogen Peroxide)',
    quantity: '',
    unit: '',
    purityNotes: '',
    formula: 'H₂O₂',
    formulaPlain: 'H2O2',
    category: 'Chemical',
    location: 'Oxidizer Storage',
    block: 'Refrigerator',
    grade: 'Oxidizer Grade',
    casNumber: '7722-84-1',
    hazardClass: 'Oxidizing Liquid / Corrosive',
    notes: 'Hydrogen Peroxide aqueous solution, strong oxidizing agent.'
  },
  {
    no: 19,
    name: 'Lactic Acid',
    quantity: '',
    unit: '',
    purityNotes: '',
    formula: 'C₃H₆O₃',
    formulaPlain: 'C3H6O3',
    category: 'Chemical',
    location: 'Main Storage',
    block: 'Main Storage',
    grade: 'Pure',
    casNumber: '50-21-5',
    hazardClass: 'Skin / Eye Corrosive',
    notes: '2-Hydroxypropanoic acid.'
  },
  {
    no: 20,
    name: 'm-Cresol',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'C₇H₈O',
    formulaPlain: 'C7H8O',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Pure',
    casNumber: '108-39-4',
    hazardClass: 'Toxic / Corrosive',
    notes: 'Organic aromatic phenol derivative (3-methylphenol).'
  },
  {
    no: 21,
    name: 'Methanol',
    quantity: '3',
    unit: 'Bottles',
    purityNotes: '',
    formula: 'CH₃OH',
    formulaPlain: 'CH3OH',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'Reagent Grade',
    casNumber: '67-56-1',
    hazardClass: 'Highly Flammable Liquid / Toxic',
    notes: 'Methyl alcohol solvent for HPLC and laboratory synthesis.'
  },
  {
    no: 22,
    name: 'Methyl Amine Solution',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'CH₃NH₂',
    formulaPlain: 'CH3NH2',
    category: 'Chemical',
    location: 'Main Storage',
    block: 'Main Storage',
    grade: 'Solution',
    casNumber: '74-89-5',
    hazardClass: 'Flammable / Corrosive / Toxic',
    notes: 'Monomethylamine aqueous solution.'
  },
  {
    no: 23,
    name: 'N,N-Dimethylformamide (DMF)',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'HCON(CH₃)₂',
    formulaPlain: 'HCON(CH3)2',
    category: 'Chemical',
    location: 'Solvent Cabinet',
    block: 'Solvent Cabinet',
    grade: 'AR',
    casNumber: '68-12-2',
    hazardClass: 'Flammable Liquid / Reproductive Toxin',
    notes: 'Polar aprotic solvent for peptide synthesis and chemical reactions.'
  },
  {
    no: 24,
    name: 'PEG 400',
    quantity: '1',
    unit: 'Bottle',
    purityNotes: '',
    formula: 'H(OCH₂CH₂)ₙOH',
    formulaPlain: 'H(OCH2CH2)nOH',
    category: 'Chemical',
    location: 'Main Storage',
    block: 'Main Storage',
    grade: 'Polymer',
    casNumber: '25322-68-3',
    hazardClass: 'Non-Hazardous Polymer',
    notes: 'Polyethylene Glycol 400 average molecular weight.'
  },
  {
    no: 25,
    name: 'Phosphoric Acid',
    quantity: '1',
    unit: 'Can',
    purityNotes: 'Can',
    formula: 'H₃PO₄',
    formulaPlain: 'H3PO4',
    category: 'Chemical',
    location: 'Acid Cabinet',
    block: 'Acid Cabinet',
    grade: 'Technical / Pure',
    casNumber: '7664-38-2',
    hazardClass: 'Corrosive',
    notes: 'Packaging: Can. Orthophosphoric acid.'
  },
  {
    no: 26,
    name: 'Sulphuric Acid',
    quantity: '2',
    unit: 'Bottles',
    purityNotes: '98%',
    formula: 'H₂SO₄',
    formulaPlain: 'H2SO4',
    category: 'Chemical',
    location: 'Acid Cabinet',
    block: 'Acid Cabinet',
    grade: '98%',
    casNumber: '7664-93-9',
    hazardClass: 'Highly Corrosive Mineral Acid',
    notes: 'Purity: 98% concentrated sulfuric acid. Highly corrosive strong mineral acid.'
  },
  {
    no: 27,
    name: 'Titanium Tetrachloride (TiCl₄)',
    quantity: '3',
    unit: 'Bottles',
    purityNotes: '2 in refrigerator',
    formula: 'TiCl₄',
    formulaPlain: 'TiCl4',
    category: 'Chemical',
    location: 'Refrigerator / Cabinet',
    block: 'Refrigerator',
    grade: 'Anhydrous',
    casNumber: '7550-45-0',
    hazardClass: 'Corrosive / Water Reactive / Toxic',
    notes: 'Storage: 2 in refrigerator, 1 in cabinet. Moisture-sensitive fuming liquid.'
  },
  {
    no: 28,
    name: 'Titanium Tetraisopropoxide (TTIP)',
    quantity: '4',
    unit: 'Bottles',
    purityNotes: '',
    formula: 'Ti[OCH(CH₃)₂]₄',
    formulaPlain: 'Ti[OCH(CH3)2]4',
    category: 'Chemical',
    location: 'Main Storage',
    block: 'Main Storage',
    grade: 'Pure TTIP',
    casNumber: '546-68-9',
    hazardClass: 'Flammable Liquid / Moisture Sensitive',
    notes: 'Titanium(IV) isopropoxide precursor for titanium dioxide nanomaterials.'
  },
  {
    no: 29,
    name: 'TMOET - Ti[OCH(CH₃)₂]₄',
    quantity: '',
    unit: '',
    purityNotes: '',
    formula: 'Ti[OCH(CH₃)₂]₄',
    formulaPlain: 'Ti[OCH(CH3)2]4',
    category: 'Chemical',
    location: 'Main Storage',
    block: 'Main Storage',
    grade: 'Titanium Alkoxide',
    casNumber: '546-68-9',
    hazardClass: 'Flammable / Moisture Sensitive',
    notes: 'Titanium alkoxide precursor / sol-gel reagent.'
  }
];

const processed = items.map(item => {
  const searchText = [
    item.no,
    item.name,
    item.category,
    item.formula,
    item.formulaPlain,
    item.quantity,
    item.unit,
    item.location,
    item.block,
    item.grade,
    item.casNumber,
    item.hazardClass,
    item.purityNotes,
    item.notes
  ].filter(Boolean).join(' ').toLowerCase();

  return {
    id: `item-${item.no}`,
    itemNo: item.no,
    name: item.name,
    category: item.category,
    formula: item.formula,
    formulaPlain: item.formulaPlain,
    quantity: item.quantity,
    unit: item.unit,
    location: item.location,
    block: item.block,
    grade: item.grade,
    notes: item.notes,
    purityNotes: item.purityNotes,
    casNumber: item.casNumber,
    hazardClass: item.hazardClass,
    searchText: searchText
  };
});

fs.writeFileSync('data/inventory.json', JSON.stringify(processed, null, 2), 'utf8');
fs.writeFileSync('data/inventory.js', 'window.LAB_INVENTORY = ' + JSON.stringify(processed, null, 2) + ';\n', 'utf8');

if (fs.existsSync('public/data')) {
  fs.writeFileSync('public/data/inventory.json', JSON.stringify(processed, null, 2), 'utf8');
}

const tsContent = `import { InventoryItem } from '../types';

export const INITIAL_INVENTORY: InventoryItem[] = ${JSON.stringify(processed, null, 2)};
`;
fs.writeFileSync('src/data/inventoryData.ts', tsContent, 'utf8');

console.log('Successfully updated all inventory data files with', processed.length, 'records.');
